# Generated by Django 2.2.10 on 2020-06-16 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torrentapp', '0002_movie_highrated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='movies',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='movies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='torrentapp.Movie'),
        ),
    ]
