# Generated by Django 2.2.10 on 2020-06-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrentapp', '0003_auto_20200616_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='movies',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='movies',
            field=models.ManyToManyField(to='torrentapp.Movie'),
        ),
    ]
