# Generated by Django 2.2.10 on 2020-06-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrentapp', '0006_auto_20200616_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='movies',
            field=models.ManyToManyField(to='torrentapp.Movie'),
        ),
    ]
