# Generated by Django 2.2.10 on 2020-06-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrentapp', '0008_auto_20200617_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='moviess',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='movies',
            field=models.ManyToManyField(to='torrentapp.Movie'),
        ),
    ]
