# Generated by Django 2.2.10 on 2020-06-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrentapp', '0009_auto_20200617_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='desc',
            field=models.TextField(max_length=90),
        ),
    ]
