# Generated by Django 2.2.10 on 2020-06-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrentapp', '0010_auto_20200617_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='desc',
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(default='movie', max_length=2000),
            preserve_default=False,
        ),
    ]
