# Generated by Django 2.2.10 on 2020-06-20 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torrentapp', '0011_auto_20200618_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='cat',
        ),
    ]
