# Generated by Django 2.2.10 on 2020-06-20 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torrentapp', '0012_remove_movie_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='user',
        ),
    ]
