# Generated by Django 2.2.10 on 2020-06-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrentapp', '0013_remove_movie_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='new',
            field=models.BooleanField(default=False),
        ),
    ]
