# Generated by Django 2.2.10 on 2020-06-22 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torrentapp', '0018_auto_20200622_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='img',
            new_name='picture',
        ),
    ]
