version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /app/entrypoint.sh
    command: gunicorn torrent.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./static_root:/app/static_root # Mapping for static files
      - ./media:/app/media # Mapping for media files
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER=redis://redis:6379/0
    depends_on:
      - redis
      - postgres

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    container_name: nginx_server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static_root:/usr/share/nginx/html/static # Nginx static files
      - ./media:/usr/share/nginx/html/media
    ports:
      - "80:80"
    depends_on:
      - web
  # frontend:
  #    build:
  #      context: .
  #      dockerfile: Dockerfile-react
  #    volumes:
  #      - ./react:/app
  #    ports:
  #      - "3000:3000"
  #    depends_on:
  #      - web #
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 33883246
    ports:
      - "5432:5432"

  celery:
    build: .
    entrypoint: /app/entrypoint.sh
    command: celery -A torrent worker --loglevel=info #--uidn = myuser
    environment:
      - CELERY_BROKER=redis://redis:6379/0
    depends_on:
      - redis
volumes:
  static_root:
  media:
