export const MOVIE_LIST_REQUEST = "MOVIE_LIST_REQUEST";
export const MOVIE_LIST_SUCCESS = "MOVIE_LIST_SUCCESS";
export const MOVIE_LIST_FAIL = "MOVIE_LIST_FAIL";

export const MOVIE_DETAIL_REQUEST = "MOVIE_DETAIL_REQUEST";
export const MOVIE_DETAIL_SUCCESS = "MOVIE_DETAIL_SUCCESS";
export const MOVIE_DETAIL_FAIL = "MOVIE_DETAIL_FAIL";

export const MOVIE_CREATE_COMMENT_REQUEST = "MOVIE_CREATE_COMMENT_REQUEST";
export const MOVIE_CREATE_COMMENT_SUCCESS = "MOVIE_CREATE_COMMENT_SUCCESS";
export const MOVIE_CREATE_COMMENT_FAIL = "MOVIE_CREATE_COMMENT_FAIL";
export const MOVIE_CREATE_COMMENT_RESET = "MOVIE_CREATE_COMMENT_RESET";

export const MOVIE_CREATE_REQUEST = "MOVIE_CREATE_REQUEST";
export const MOVIE_CREATE_SUCCESS = "MOVIE_CREATE_SUCCESS";
export const MOVIE_CREATE_FAIL = "MOVIE_CREATE_FAIL";
export const MOVIE_CREATE_RESET = "MOVIE_CREATE_RESET";

export const MOVIE_UPDATE_REQUEST = "MOVIE_UPDATE_REQUEST";
export const MOVIE_UPDATE_SUCCESS = "MOVIE_UPDATE_SUCCESS";
export const MOVIE_UPDATE_FAIL = "MOVIE_UPDATE_FAIL";
export const MOVIE_UPDATE_RESET = "MOVIE_UPDATE_RESET";

export const MOVIE_FILTER_REQUEST = "MOVIE_FILTER_REQUEST";
export const MOVIE_FILTER_SUCCESS = "MOVIE_FILTER_SUCCESS";
export const MOVIE_FILTER_FAIL = "MOVIE_FILTER_FAIL";
export const MOVIE_FILTER_RESET = "MOVIE_FILTER_RESET";
